### ISSUE TITLE
Corrupted mesh with GLSL Compute on AMD hardware

### ISSUE THREAD

**Issue by Nazg-Gul** [PixarAnimationStudios/OpenSubdiv#735]
Using GLSL Compute on AMD hardware causes mesh to be totally corrupted.

Test configuration:

OpenSsubdiv hash: 3a20df2
Operation system: Win 8 64bit
GPU: Fire Pro W8000
Driver: Catalyst 15.7

Steps to reproduce: with glView application simply switch to GLSL Compute

The sane issue was reported to Blender's bug tracker when using AMD A10-6800K and A10-7850K.

**Comment by anshuarya** [comment]
Was this fixed by #738?

**Comment by jcowles** [comment]
We believe this issue is not yet resolved, David can still reproduce it on his AMD hardware even with the patch from #738.

--
Jeremy

**Comment by anshuarya** [comment]
Forwarding info from Qun Lin:
"It is an application issue. Application forgot to specify the block layout for all shader storage blocks in compute shader.
They assume the default layout is std430. But according to spec, the default layout is shared, which layout is dependent on driver’s implementation, and app should query each member’s offset if they want to use shared layout.
To fix this issue, application only needs to add following line at the beginning of the shader source code:
layout(std430) buffer;
Attached is modified compute shader, in case you need it. With these modified shaders, corruption disappears."

Links to compute shader code referenced above:
https://dl.dropboxusercontent.com/u/3047603/computeshader1.txt
https://dl.dropboxusercontent.com/u/3047603/computeshader2.txt

**Comment by davidgyu** [comment]
Yup, that sounds right! I just tried setting the buffer layout and in my
local build and the GLSL Compute evaluator is now working correctly on my
AMD systems (D700 and R9 290X).

Thanks!
-David

**Comment by anshuarya** [comment]
Yep, I have it working on multiple AMD APU systems as well, A10-6800K, A10-7850K, A10-7890K, and FX8800P.

**Comment by jcowles** [comment]
This is excellent, thank you!

**Comment by jcowles** [comment]
Fixed by #742
